pull_request_rules:
  - name: Automatic merge when all status checks pass
    conditions:
      - status-success=security/snyk (Distribute Aid)
      - status-success=tests
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
      label:
        add:
          - mergify
  - name: Automatically approve trusted service PRs
    conditions:
      - author~=^(snyk-bot|dependabot\[bot\]|renovate\[bot\])$
    actions:
      review:
        message: Automatically approved because PR is by a trusted service
